name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env
      run: cp tests/.env .env

    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.1.0

    - name: Install mongodb php-extension
      run: sudo apt install php7.4-mongodb

    - name: Run test suites
      run: composer run-script test
